spring.application.name=UserService
Spring.profile.active = "default"
server.port=8085
#spring.config.import=configserver
spring.cloud.config.import-check.enabled=false

#######database settings##################################
spring.datasource.url=jdbc:mysql://localhost:3306/userservice?autoReconnect=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.hikari.maximumpoolsize=10
spring.datasource.hikari.minimum-idle=5


spring.jpa-defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

#spring.h2.console.enabled=true
spring.main.allow-bean-definition-overriding=true

###############server-settings################################
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false






